### ISSUE TITLE
Nice Works!

### ISSUE THREAD

**Issue by lizzus** [AchimPieters/ESP8266-HomeKit-Lock#1]
Nice Work!. What gpio you use?
Can I Install with OTA?

**Comment by AchimPieters** [comment]
I'm still working on this one, I have a few issues that I need to run by Maxim, before I can release this one. So I'll keep you updated.

And for the future reference this one is installable with OTA.

**Comment by lizzus** [comment]
Great! Do you think you will add features avaible on EVE app?

**Comment by AchimPieters** [comment]
What I know off all of the assesories that maxim made are available in the EVE app.

**Comment by lizzus** [comment]
yes, but i mean for example if you want add inching to lock (like made Josè on Ravencore)
I have a homekit group here. I suggest to people how to create devices with alternative firmware. https://www.twibuk.com/homekititalia and here https://www.facebook.com/groups/homekititalia/ (some guidelines are here: https://www.twibuk.com/blogs). Is not spam, and i Invite you to enter in our Group! we will be very very very very very happy :-)

**Comment by AchimPieters** [comment]
Thank you for your invite :smiley:, but it's all in spanis, and I don't speak spanis :flushed:

**Comment by lizzus** [comment]
is italian... :-) but you can write in english
